name: Continuous Integration

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcc:
    name: GCC
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - gcc: "4.8"
            archive: bionic
          - gcc: "10"
            archive: focal
            cxxflags: -funsigned-char # Issue #1715
          - gcc: "14"
            test: "ppa:ubuntu-toolchain-r/test"
          - gcc: "16"
            test: "ppa:ubuntu-toolchain-r/test"
    steps:
      - name: Workaround for actions/runner-images#9491
        run: sudo sysctl vm.mmap_rnd_bits=28

      - name: Install archived toolchain
        if: matrix.archive
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ ${{ matrix.archive }} main'
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ ${{ matrix.archive }} universe'
          sudo apt-get update -y
          sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
        timeout-minutes: 5

      - name: Install toolchain test build
        if: matrix.test
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
        timeout-minutes: 5

      - name: Checkout
        uses: actions/checkout@v4
        timeout-minutes: 1

      - name: Configure
        if: matrix.gcc != 'latest'
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        env:
          CC: gcc-${{ matrix.gcc }}
          CXX: g++-${{ matrix.gcc }}
          CXXFLAGS: ${{ matrix.cxxflags }}
        timeout-minutes: 1

      - name: Build
        run: cmake --build .
        timeout-minutes: 10

      - name: Test
        run: ctest --output-on-failure -C Debug .
        env:
          UBSAN_OPTIONS: print_stacktrace=1
        timeout-minutes: 2

  clang:
    name: Clang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        env:
          CC: clang
          CXX: clang++
      - name: Build
        run: cmake --build .
      - name: Test
        run: ctest --output-on-failure -C Debug .

  arduino:
    name: Build Arduino examples
    runs-on: ubuntu-latest
    needs:
      - gcc
      - clang
    strategy:
      fail-fast: false
      matrix:
        include:
          - core: esp8266:esp8266
            board: esp8266:esp8266:d1_mini
            opts: --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          - core: esp32:esp32
            board: esp32:esp32:esp32
            libraries: Ethernet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install arduino-cli
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh

      - name: Install libraries
        if: matrix.libraries
        run: arduino-cli lib install ${{ matrix.libraries }}

      - name: Install core
        run: |
          arduino-cli ${{ matrix.opts }} core update-index
          arduino-cli ${{ matrix.opts }} core install ${{ matrix.core }}

      - name: Build examples
        run: scripts/build-arduino-examples.sh ${{ matrix.board }}
